use estacionamento;

ALTER TABLE CLIENTE ADD Endereco Varchar(80);

ALTER TABLE ESTACIONAMENTOS MODIFY COLUMN Observacao Varchar (8000);

ALTER TABLE ESTACIONAMENTOS DROP PRIMARY KEY;
ALTER TABLE ESTACIONAMENTOS DROP Codigo_registro;
ALTER TABLE ESTACIONAMENTOS ADD Codigo_registro Int (10) PRIMARY KEY AUTO_INCREMENT;
